name: Release
on:
  workflow_run:
    workflows: ['Snyk Security Check', 'Tests']
    branches: [master]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
